/*
Copyright 2017 The Gardener Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
package driver

import (
	"os"
	"fmt"

	v1alpha1 "github.com/gardener/node-controller-manager/pkg/apis/machine/v1alpha1"
	corev1 "k8s.io/api/core/v1" 

	"github.com/golang/glog"
	"github.com/Azure/azure-sdk-for-go/arm/compute"
	"github.com/Azure/azure-sdk-for-go/arm/network"
	"github.com/Azure/azure-sdk-for-go/arm/disk"
	"github.com/Azure/go-autorest/autorest"
	"github.com/Azure/go-autorest/autorest/azure"
	"github.com/Azure/go-autorest/autorest/to"
	"github.com/Azure/go-autorest/autorest/utils"
)

type AzureDriver struct {
	AzureMachineClass  *v1alpha1.AWSMachineClass
	CloudConfig		   *corev1.Secret
	UserData 		   string
	InstanceId		   string
}

func NewAzureDriver(create func() (string, error), delete func() error, existing func() (string, error)) Driver {
	return &AWSDriver{}
}

// Create
func (d *AzureDriver) Create() (string, string, error) {

	//VM-name has to be in small letters
	vmName := "sample-vm"
	createVM(vmName, "image-publisher", "image-offer", "image-sku")

    return vmName, vmName, nil
}

// Delete
func (d *AzureDriver) Delete() error {
    
    //VM-name has to be in small letters
	vmName := "sample-vm"
	nicName := vmName + "-nic"
	diskName := vmName + "-os-disk"

	cancel := make(chan struct{})

	_, errChan := vmClient.Delete(groupName, vmName, cancel)
	onErrorFail(<-errChan, fmt.Sprintf("vmClient.Delete failed for '%s'", vmName))
	glog.Infof("Deleted '%s' virtual machine...\n", vmName)

	_, errChan = interfacesClient.Delete(groupName, nicName, cancel)
	onErrorFail(<-errChan, fmt.Sprintf("interfacesClient.Delete for NIC '%s' failed", nicName))
	glog.Infof("\tDeleted NIC '%s' successfully\n", nicName)

	_, errChan = diskClient.Delete(groupName, diskName, cancel)
	onErrorFail(<-errChan, fmt.Sprintf("diskClient.Delete for NIC '%s' failed", nicName))
	glog.Infof("\tDeleted Disk '%s' successfully\n", diskName)
    
    return nil
}

// GetExisting
func (d *AzureDriver) GetExisting() (string, error) {
	return d.InstanceId, nil
}

func init() {
	subscriptionID := getEnvVarOrExit("AZURE_SUBSCRIPTION_ID")
	authorizer, err := utils.GetAuthorizer(azure.PublicCloud)
	onErrorFail(err, "utils.GetAuthorizer failed")
	createClients(subscriptionID, authorizer)
}

var (
	groupName   = "sample-group-name"
	location    = "westeurope"
	vNetName    = "sample-vNet-name"
	subnetName  = "workers"

	interfacesClient network.InterfacesClient
	vmClient         compute.VirtualMachinesClient
	subnetClient     network.SubnetsClient
	diskClient    	 disk.DisksClient
)

// createVM creates a VM in the provided subnet.
func createVM(vmName, publisher, offer, sku string) {

	glog.Infof("\tGet subnet info for subnet '%s'...\n", subnetName)
	subnet, err := subnetClient.Get(groupName, vNetName, subnetName, "")
	onErrorFail(err, fmt.Sprintf("subnetClient.Get failed for subnet '%s'", subnetName))
	nicParameters := createNIC(vmName, &subnet)

	cancel := make(chan struct{})
	glog.Infof("Create '%s' VM...\n", vmName)
	vm := setVMparameters(vmName, publisher, offer, sku, *nicParameters.ID)
	vmResult, errChan := vmClient.CreateOrUpdate(groupName, vmName, vm, cancel)
	onErrorFail(<-errChan, "createVM failed")

	glog.Infof("vmResult: '%s'\n", vmResult)
}

// setVMparameters builds the VirtualMachine argument for creating or updating a VM.
func setVMparameters(vmName, publisher, offer, sku, nicID string) compute.VirtualMachine {
	
	tags := map[string]*string{
		"Name": &vmName,
		"kubernetes.io-cluster-name": to.StringPtr("1"),
		"kubernetes.io-role-node": to.StringPtr("1"),
	}

	return compute.VirtualMachine{
		Location: &location,
		VirtualMachineProperties: &compute.VirtualMachineProperties{
			HardwareProfile: &compute.HardwareProfile{
				VMSize: compute.VirtualMachineSizeTypesStandardDS1V2,
			},
			StorageProfile: &compute.StorageProfile{
				ImageReference: &compute.ImageReference{
					Publisher: &publisher,
					Offer:     &offer,
					Sku:       &sku,
					Version:   to.StringPtr("image-reference-version"),
				},
				OsDisk: &compute.OSDisk{
					Name: to.StringPtr(vmName + "-os-disk"),
					Caching: compute.CachingTypesNone,
					ManagedDisk: &compute.ManagedDiskParameters{
						StorageAccountType: compute.StandardLRS,
					},
					DiskSizeGB: to.Int32Ptr(35),
					CreateOption: compute.DiskCreateOptionTypesFromImage,
				},
			},
			OsProfile: &compute.OSProfile{
				ComputerName:  &vmName,
				AdminUsername: to.StringPtr("admin"),
				CustomData: to.StringPtr("I2Nsb3VkLWNvbmZpZwoKY29yZW9zOgogIHVwZGF0ZToKICAgIHJlYm9vdC1zdHJhdGVneTogb2ZmCiAgdW5pdHM6CiAgLSBuYW1lOiBkb2NrZXIuc2VydmljZQogICAgZHJvcC1pbnM6CiAgICAtIG5hbWU6IDEwLWRvY2tlci1vcHRzLmNvbmYKICAgICAgY29udGVudDogfAogICAgICAgIFtTZXJ2aWNlXQogICAgICAgIEVudmlyb25tZW50PSJET0NLRVJfT1BUUz0tLWxvZy1vcHQgbWF4LXNpemU9NjBtIC0tbG9nLW9wdCBtYXgtZmlsZT0zIgogIC0gbmFtZToga3ViZWxldC5zZXJ2aWNlCiAgICBjb21tYW5kOiBzdGFydAogICAgZW5hYmxlOiB0cnVlCiAgICBjb250ZW50OiB8CiAgICAgIFtVbml0XQogICAgICBEZXNjcmlwdGlvbj1rdWJlbGV0IGRhZW1vbgogICAgICBEb2N1bWVudGF0aW9uPWh0dHBzOi8va3ViZXJuZXRlcy5pby9kb2NzL2FkbWluL2t1YmVsZXQKICAgICAgQWZ0ZXI9ZG9ja2VyLnNlcnZpY2UKICAgICAgV2FudHM9ZG9ja2VyLnNvY2tldCBycGMtc3RhdGQuc2VydmljZQogICAgICBbSW5zdGFsbF0KICAgICAgV2FudGVkQnk9bXVsdGktdXNlci50YXJnZXQKICAgICAgW1NlcnZpY2VdCiAgICAgIFJlc3RhcnQ9YWx3YXlzCiAgICAgIFJlc3RhcnRTZWM9MTAKICAgICAgRW52aXJvbm1lbnRGaWxlPS9ldGMvZW52aXJvbm1lbnQKICAgICAgRXhlY1N0YXJ0UHJlPS0vYmluL2RvY2tlciBybSAtZiBrdWJlbGV0CiAgICAgIEV4ZWNSZWxvYWQ9LS9iaW4vZG9ja2VyIHJlc3RhcnQga3ViZWxldAogICAgICBFeGVjU3RhcnQ9L29wdC9iaW4va3ViZWxldCBcCiAgICAgICAgLS1hbGxvdy1wcml2aWxlZ2VkPXRydWUgXAogICAgICAgIC0tYW5vbnltb3VzLWF1dGg9ZmFsc2UgXAogICAgICAgIC0tY2xpZW50LWNhLWZpbGU9L3Zhci9saWIva3ViZWxldC9jYS5jcnQgXAogICAgICAgIC0tYXV0aGVudGljYXRpb24tdG9rZW4td2ViaG9vayBcCiAgICAgICAgLS1hdXRob3JpemF0aW9uLW1vZGU9V2ViaG9vayBcCiAgICAgICAgLS1jZ3JvdXAtcm9vdD0iLyIgXAogICAgICAgIC0tY2xvdWQtcHJvdmlkZXI9YXp1cmUgXAogICAgICAgIC0tY2x1c3Rlci1kbnM9IjEwMC42NC4wLjEwIiBcCiAgICAgICAgLS1jbHVzdGVyLWRvbWFpbj1jbHVzdGVyLmxvY2FsIFwKICAgICAgICAtLWVuYWJsZS1kZWJ1Z2dpbmctaGFuZGxlcnM9dHJ1ZSBcCiAgICAgICAgLS1ldmljdGlvbi1oYXJkPSJtZW1vcnkuYXZhaWxhYmxlPDEwME1pLG5vZGVmcy5hdmFpbGFibGU8NSUsbm9kZWZzLmlub2Rlc0ZyZWU8NSUsaW1hZ2Vmcy5hdmFpbGFibGU8NSUsaW1hZ2Vmcy5pbm9kZXNGcmVlPDUlIiBcCiAgICAgICAgLS1ldmljdGlvbi1zb2Z0PSJtZW1vcnkuYXZhaWxhYmxlPDIwME1pLG5vZGVmcy5hdmFpbGFibGU8MTAlLG5vZGVmcy5pbm9kZXNGcmVlPDEwJSxpbWFnZWZzLmF2YWlsYWJsZTwxMCUsaW1hZ2Vmcy5pbm9kZXNGcmVlPDEwJSIgXAogICAgICAgIC0tZXZpY3Rpb24tc29mdC1ncmFjZS1wZXJpb2Q9Im1lbW9yeS5hdmFpbGFibGU9MW0zMHMsbm9kZWZzLmF2YWlsYWJsZT0xbTMwcyxub2RlZnMuaW5vZGVzRnJlZT0xbTMwcyxpbWFnZWZzLmF2YWlsYWJsZT0xbTMwcyxpbWFnZWZzLmlub2Rlc0ZyZWU9MW0zMHMiIFwKICAgICAgICAtLWV2aWN0aW9uLW1heC1wb2QtZ3JhY2UtcGVyaW9kPSI5MCIgXAogICAgICAgIC0tZXZpY3Rpb24tcHJlc3N1cmUtdHJhbnNpdGlvbi1wZXJpb2Q9IjRtIiBcCiAgICAgICAgLS1pbWFnZS1nYy1oaWdoLXRocmVzaG9sZD01MCBcCiAgICAgICAgLS1pbWFnZS1nYy1sb3ctdGhyZXNob2xkPTQwIFwKICAgICAgICAtLWt1YmVjb25maWc9Ii92YXIvbGliL2t1YmVsZXQva3ViZWNvbmZpZyIgXAogICAgICAgIC0ta3ViZS1yZXNlcnZlZD1tZW1vcnk9IjFHaSIgXAogICAgICAgIC0tbmV0d29yay1wbHVnaW49ImNuaSIgXAogICAgICAgIC0tbm9kZS1sYWJlbHM9Imt1YmVybmV0ZXMuaW8vcm9sZT1ub2RlLG5vZGUtcm9sZS5rdWJlcm5ldGVzLmlvL25vZGU9LHdvcmtlci5nYXJkZW4uc2FwY2xvdWQuaW8vZ3JvdXA9Y3B1LXdvcmtlciIgXAogICAgICAgIC0tcmVxdWlyZS1rdWJlY29uZmlnPXRydWUgXAogICAgICAgIC0tY25pLWJpbi1kaXI9L29wdC9jbmkvYmluLyBcCiAgICAgICAgLS1jbmktY29uZi1kaXI9L2V0Yy9jbmkvbmV0LmQvIFwKICAgICAgICAtLWNsb3VkLWNvbmZpZz0vdmFyL2xpYi9rdWJlbGV0L2Nsb3VkcHJvdmlkZXIuY2ZnIFwKICAgICAgICAtLXY9MgogIC0gbmFtZTogZG9ja2VyLW1vbml0b3Iuc2VydmljZQogICAgY29tbWFuZDogc3RhcnQKICAgIGVuYWJsZTogdHJ1ZQogICAgY29udGVudDogfAogICAgICBbVW5pdF0KICAgICAgRGVzY3JpcHRpb249RG9ja2VyLW1vbml0b3IgZGFlbW9uCiAgICAgIEFmdGVyPWt1YmVsZXQuc2VydmljZQogICAgICBbSW5zdGFsbF0KICAgICAgV2FudGVkQnk9bXVsdGktdXNlci50YXJnZXQKICAgICAgW1NlcnZpY2VdCiAgICAgIFJlc3RhcnQ9YWx3YXlzCiAgICAgIEVudmlyb25tZW50RmlsZT0vZXRjL2Vudmlyb25tZW50CiAgICAgIEV4ZWNTdGFydD0vb3B0L2Jpbi9oZWFsdGgtbW9uaXRvciBkb2NrZXIKICAtIG5hbWU6IGt1YmVsZXQtbW9uaXRvci5zZXJ2aWNlCiAgICBjb21tYW5kOiBzdGFydAogICAgZW5hYmxlOiB0cnVlCiAgICBjb250ZW50OiB8CiAgICAgIFtVbml0XQogICAgICBEZXNjcmlwdGlvbj1LdWJlbGV0LW1vbml0b3IgZGFlbW9uCiAgICAgIEFmdGVyPWRvY2tlci1tb25pdG9yLnNlcnZpY2UKICAgICAgW0luc3RhbGxdCiAgICAgIFdhbnRlZEJ5PW11bHRpLXVzZXIudGFyZ2V0CiAgICAgIFtTZXJ2aWNlXQogICAgICBSZXN0YXJ0PWFsd2F5cwogICAgICBFbnZpcm9ubWVudEZpbGU9L2V0Yy9lbnZpcm9ubWVudAogICAgICBFeGVjU3RhcnQ9L29wdC9iaW4vaGVhbHRoLW1vbml0b3Iga3ViZWxldAogIC0gbmFtZTogc3lzdGVtZC1zeXNjdGwuc2VydmljZQogICAgY29tbWFuZDogcmVzdGFydAogICAgZW5hYmxlOiB0cnVlCndyaXRlX2ZpbGVzOgotIHBhdGg6IC9vcHQvYmluL2t1YmVsZXQKICBwZXJtaXNzaW9uczogMDc1NQogIGNvbnRlbnQ6IHwKICAgICMhL2Jpbi9iYXNoCiAgICBkb2NrZXIgcnVuIFwKICAgICAgLS1uZXQ9aG9zdCBcCiAgICAgIC0tcGlkPWhvc3QgXAogICAgICAtLXByaXZpbGVnZWQgXAogICAgICAtLW5hbWU9a3ViZWxldCBcCiAgICAgIC0tcmVzdGFydD1vbi1mYWlsdXJlOjUgXAogICAgICAtdiAvZGV2Oi9kZXY6cncgXAogICAgICAtdiAvZXRjL2NuaTovZXRjL2NuaTpybyBcCiAgICAgIC12IC9vcHQvY25pOi9vcHQvY25pOnJvIFwKICAgICAgLXYgL2V0Yy9zc2w6L2V0Yy9zc2w6cm8gXAogICAgICAtdiAvdXNyL3NoYXJlL2NhLWNlcnRpZmljYXRlczovdXNyL3NoYXJlL2NhLWNlcnRpZmljYXRlczpybyBcCiAgICAgIC12IC9ldGMvcmVzb2x2LmNvbmY6L2V0Yy9yZXNvbHYuY29uZiBcCiAgICAgIC12IC9zeXM6L3N5czpybyBcCiAgICAgIC12IC92YXIvbGliL2RvY2tlcjovdmFyL2xpYi9kb2NrZXI6cncgXAogICAgICAtdiAvdmFyL2xvZzovdmFyL2xvZzpydyBcCiAgICAgIC12IC92YXIvbGliL2NuaTovdmFyL2xpYi9jbmk6c2hhcmVkIFwKICAgICAgLXYgL3Zhci9ydW46L3Zhci9ydW46cncgXAogICAgICAtdiAvdmFyL2xpYi9rdWJlbGV0Oi92YXIvbGliL2t1YmVsZXQ6c2hhcmVkIFwKICAgICAgLXYgL2V0Yy9vcy1yZWxlYXNlOi9ldGMvb3MtcmVsZWFzZTpybyBcCiAgICAgIGdjci5pby9nb29nbGVfY29udGFpbmVycy9oeXBlcmt1YmU6djEuOC4yIFwKICAgICAgLi9oeXBlcmt1YmUga3ViZWxldCBcCiAgICAiJEAiCi0gcGF0aDogL3Zhci9saWIva3ViZWxldC9jbG91ZHByb3ZpZGVyLmNmZwogIHBlcm1pc3Npb25zOiAwNjQ0CiAgZW5jb2Rpbmc6IGI2NAogIGNvbnRlbnQ6IHwKICAgIFkyeHZkV1E2SUVGYVZWSkZVRlZDVEVsRFEweFBWVVFLZEdWdVlXNTBTV1E2SURReVpqYzJOelpqTFdZME5UVXROREl6WXkwNE1tWTJMV1JqTW1RNU9UYzVNV0ZtTndwemRXSnpZM0pwY0hScGIyNUpaRG9nTVRjNU9HRXpOalF0WW1ZME55MDBNREF3TFdGbU16RXRZek0yWWpFME9ESTNZVE0yQ25KbGMyOTFjbU5sUjNKdmRYQTZJSE5vYjI5MExXa3pOREU0T0RndGFUTTBNVGc0T0MwMUxYTmhjR3M0Y3dwc2IyTmhkR2x2YmpvZ2QyVnpkR1YxY205d1pRcDJibVYwVG1GdFpUb2djMmh2YjNRdGFUTTBNVGc0T0MxcE16UXhPRGc0TFRVdGRtNWxkQXB6ZFdKdVpYUk9ZVzFsT2lCM2IzSnJaWEp6Q25ObFkzVnlhWFI1UjNKdmRYQk9ZVzFsT2lCdWIyUmxjd3B5YjNWMFpWUmhZbXhsVG1GdFpUb2dkMjl5YTJWeVgzSnZkWFJsWDNSaFlteGxDbkJ5YVcxaGNubEJkbUZwYkdGaWFXeHBkSGxUWlhST1lXMWxPaUIzYjNKclpYSnpMV0YyYzJWMENtRmhaRU5zYVdWdWRFbGtPaUE1TjJZMlpXUXhOeTA0WW1GbUxUUmxOell0WVRBMFl5MHhNRGRrTW1SbE9XRmxZeklLWVdGa1EyeHBaVzUwVTJWamNtVjBPaUJuTVZvMWRXWnJaV0ZYY1dKUlJVOVNhRkpzZFhkeVQwNW5iaTlQUVZOVU9XZ3JjMmhuZFRRMFYwbEpQUXBqYkc5MVpGQnliM1pwWkdWeVFtRmphMjltWmpvZ2RISjFaUXBqYkc5MVpGQnliM1pwWkdWeVFtRmphMjltWmxKbGRISnBaWE02SURZS1kyeHZkV1JRY205MmFXUmxja0poWTJ0dlptWkZlSEJ2Ym1WdWREb2dNUzQxQ21Oc2IzVmtVSEp2ZG1sa1pYSkNZV05yYjJabVJIVnlZWFJwYjI0NklERXlNQXBqYkc5MVpGQnliM1pwWkdWeVFtRmphMjltWmtwcGRIUmxjam9nTVM0d0NtTnNiM1ZrVUhKdmRtbGtaWEpTWVhSbFRHbHRhWFE2SUhSeWRXVUtZMnh2ZFdSUWNtOTJhV1JsY2xKaGRHVk1hVzFwZEZGUVV6b2dNQzQxQ21Oc2IzVmtVSEp2ZG1sa1pYSlNZWFJsVEdsdGFYUkNkV05yWlhRNklEVT0KLSBwYXRoOiAvdmFyL2xpYi9rdWJlbGV0L2t1YmVjb25maWcKICBwZXJtaXNzaW9uczogMDY0NAogIGVuY29kaW5nOiBiNjQKICBjb250ZW50OiB8CiAgICBMUzB0Q21Gd2FWWmxjbk5wYjI0NklIWXhDbXRwYm1RNklFTnZibVpwWndwamRYSnlaVzUwTFdOdmJuUmxlSFE2SUhOb2IyOTBMV2t6TkRFNE9EZ3RhVE0wTVRnNE9DMDFDbU5zZFhOMFpYSnpPZ290SUc1aGJXVTZJSE5vYjI5MExXa3pOREU0T0RndGFUTTBNVGc0T0MwMUNpQWdZMngxYzNSbGNqb0tJQ0FnSUdObGNuUnBabWxqWVhSbExXRjFkR2h2Y21sMGVTMWtZWFJoT2lCTVV6QjBURk14UTFKVlpFcFVhVUpFVWxaS1ZWTlZXa3BSTUVaVlVsTXdkRXhUTUhSRGF6RktVMVZOZVZKRlRrUlJWMDVFV2pCR00xTlZTa0phTUd4VFVWVnplbFJ1VGtOVWVtUnVWWHBCY2xFeWRHaFdiV2cwVFhwS2MyVnNWak5TUmtaYVUydDBkbGRyYkc5a2JVNVBVVlpHUmxSRlNsSlJXR05MVW14U1JsWkZNVU5TVldSQ1RWWldSbEZZYUU1VE1rVjZWbTFzWVZkRmNERlhiR2hUWWtkT05sRlhWa2RrZWtJMFZEQlNRbVZGTVZWU1dHUlFWa1ZXTmxSVlVtdFpWVm96VFVoc1VGSkZSalJVVmxKR1pIZHdVRlpGVmpaVVZWSnJXVlV4UTFaWWFFWmxhMFpUVVcxa1QxWnJTa0pVVmxKRVlsaFJlRmRYTVZkbFYwcDBWbXBDWVZkRk1UTmFNbVJHWVZVeFFrMUZaRVJWTTBaSVZUQnNhVTB3VWxKU1ZVcENWVlpXUWtOclJUQlRWVXBGWkRCR00xb3laRVpUTUVaMlUxVktRbFZWVFhsaWJsbDJZVE5LUlZONldrZE9ibWhHUzNwb2VWRnJTbmRXYkZwUll6RndNVlF6Y0hwV2EwNWFaRWhOTUU0d2N6TmhRemxwVmpJMVZXSXlPRXRYV0c5M1QxTnpNVkZWVms5VWJGSjVVVlUwZGxFeWRHMVdWM2hGV2xaS1dHRnVZM2hTUkZaM1lVVnNha3N3T1doWk1ERlNUa1ZhYzFSWFZtNVpWMVV5VTJwb2RWRXlXakJXUjBseVVraGtiVkpZVlRSU1FYQlVUMVJHU1dOSVNuSmpibVIyV25rNWNGUkZOREJXU0ZKVlducHNObVZWTkhwWFNGWjBaSHBHVWs1SFRtMWpSRVowVGtkYVNtRXdWbEpXTTFJMVVqTktlRTlIU1hsVVJWcEhZa1pzVm1GVmNHNU9WMnh5UTIwNWIweDZWbTFqYTBaV1ZETm5NMDlFU2pGaFJtdzJZM2wwV21GVVFYZE9ibU4zWXpGd2VVOVRPVkJrYm5Cb1pEQnJlbEpVYkRCUk1scHBUVzV3VmxSWE1VcFRSa1pFWVZkd1ZrMXNXVFJXVjFvelRqQm5TMUpZVm5GaGJWSnBVVEZDZGxsVE9ETldRemxIVFd4a1lXRkdiR3hSYmxGMllXMVZjbUZXVG0xaldFb3hZbTA1YVdOc2FFOVhhVGxGWlVjeGJsRXpUbkJUZWs1clRWZEdlbG94UmxoTmVtUjFVMnR3YzFaQmNGVlRWMmd3WTFST1JVOVlVbnBqVmtaUVV6SnZjazVzUlRSVGVtTjVWR3BDZDFWdFRuRlVTRUpQVWxWNFJrOVhOWEpTYTFVMVVWZGtUbEZyUmtKU01uQktaV3RHYjFSVlJUQlNNRVY0VmxkU1JXUXdWa05EYVRrelZWVldRbVF3YkVOalIzQkNWVVZLYmxSc1drbFZhekZEVVZkWk5GSlZTbFZSVlZKQ1ZWVm5kbFJWUlhkU01FNVVZMVZrVkZOWFNYcFNSa1pHVVd0T00xWlZSa0pPUld4RFVWWkdRbG94UlRKWlYyZExWREZTZFU5WVFtOVZlbFpVWXpCR1dsWXpWWGxXZWtaNVpHeEdjRko2VWxsVFJHUnhWSHBrY1dWc2JFTlZWWGN3VFZadk5HRnJSVFZaYmxwd1kxZFJORmt6Um5aUldGVjNWVlY0UW1SVmVGbGFWR3hGVDFGd2FscHJTa3RTYkU1WVkxZHNWR0l5U2tOV01GVXpZek5GZDFKVlZqRmFha1pJWkVaV2NHRlZXa3hWTURWRVdUSlJlRlpHYkdGYVJ6UTBUREpqZVdSc1ozSlVlazVGVVhwU2JHVlZPVVpSVlVaVllVaFdjVU5xV2t0VVZWSlhUV3QwZFZwSVZsVmlNRkp4V1RCU1NtTkVRbTFaTVZsNlUwUm9jVlZ0TlhoUlZrNUpWREZXTTFWck5UWlJhbEpwVlVkM2QyUXhhREZSV0d4eVZVVktjMDFyUmtWV1Z6bFVVVmRPTkUxWGEwdFJNa3BSV2pOWk1WVldiREZXTUZvMVRYcE5lV1ZZV25walNFRjRUREJ2Y2xsV1RtaGlibHBUVGtkNE0yTkdXazFqVkdoV1pESmtkMDFHU25sWGJFWndXa2N4ZG1KNlVrbGlNVlpXVmtSc1RHTXdOWFJQUVhCUllXeEtjRkY1T1doYWJGWlpUbGhvU1ZwWFZtNU5XR2hPWTIxT1Mxb3lPWGRYUlVwU1VsZFJOR0pFWkVwa2JXUnhWbTFrTldWR2NGZGpNVlpVVVRGS1RrNUhPVWhMTUhBelZtMTRVR0pWZEhCa1JsSTJRMnRXV0ZreU5XNVNXRnA1WVRJeGJrMTZSVEZVVjBsTFRGTXdkRXhUTVVaVWExRm5VVEJXVTFaRmJFZFRWVTVDVmtWVmRFeFRNSFJNVVc4OUNpQWdJQ0J6WlhKMlpYSTZJR2gwZEhCek9pOHZNVEEwTGpRd0xqSXlPUzQxTlFwamIyNTBaWGgwY3pvS0xTQnVZVzFsT2lCemFHOXZkQzFwTXpReE9EZzRMV2t6TkRFNE9EZ3ROUW9nSUdOdmJuUmxlSFE2Q2lBZ0lDQmpiSFZ6ZEdWeU9pQnphRzl2ZEMxcE16UXhPRGc0TFdrek5ERTRPRGd0TlFvZ0lDQWdkWE5sY2pvZ2MyaHZiM1F0YVRNME1UZzRPQzFwTXpReE9EZzRMVFVLZFhObGNuTTZDaTBnYm1GdFpUb2djMmh2YjNRdGFUTTBNVGc0T0MxcE16UXhPRGc0TFRVS0lDQjFjMlZ5T2dvZ0lDQWdZMnhwWlc1MExXTmxjblJwWm1sallYUmxMV1JoZEdFNklFeFRNSFJNVXpGRFVsVmtTbFJwUWtSU1ZrcFZVMVZhU2xFd1JsVlNVekIwVEZNd2RFTnJNVXBUVlUxMllXdE9SRkZYVm1oYU1FWXpVMVZLUWxvd2JGTlJWa0pzV1ZaTk1WcFZhRWhqYms1M1ZtNVNObUpXVGtWaU1uTnlWMFpzTTFKR1JscFRhM1IyVjJ0c2IyUnRUazlSVmtaR1ZFVktVbEZZWTB0U2JGSkdWa1V4UTFKVlpFSk5WbFpHVVZob1RsTXlSWHBXYld4aFYwVndNVmRzYUZOaVIwNDJVVmRXUjJSNlFqUlVNRkpDWlVVeFZWSllaRkJXUlZZMlZGWlNRMWxWV2pOTlNHeFFVa1ZHTkZSV1VrWmtkM0JRVmtWV05sUldVa05aVlRGRVlUTm9SMVpGUmxWUmJXUlBWbXRLUW1JeFVrVlRSVFF4V1hwT1UySkhTbFZqU0ZacFRXeEtjMWt6Y0VaVlZURkNUa1ZrUWsxV1ZrWlJXR2hPVTBkRmVsWnRiR0ZXTTJoelEyMVNSVkV3VGtKVk1Hd3pVa1pHV2xOcmRIWlhhMnh2WkcxT1QxRldSa1pSYTBwU1VWVlNibG93VmxGUlZWSkVVVEJHVW1Jd1RtNWFNRlpEVVZVMVZWVkVXbkZoTVd4clZVaEZjbGRWYUVOTlV6bGhXVlZOUzFOWFJYSlpNbEpTWlZWd1JHTldRa3RoUkVVeFZFaFNiRkpITVU5TU0wMTZZa1pXTkZKVmJEQmlSVlp0WTBSQ2NsbFhVa3BSYVRsYVVtcGFTbUl3VWxWVVNGWjJWMnMwTkZKVlozSmhWbXhhVGxSb1EyTkJiM2RSZWsweFUyNVdlRXQ2VG5aVlNFSlVXbnBTV0dOV1NrMU5hazB5WWtaYVFrc3hXakpsYXpsWVZGVlJNV0pVVm5GYVIxWnpVbXRLZUZSWFNUUmFWMnhGVTFkd2JWRjVPVWxWYW14d1dXdFdhRlZ0YUVaRGJHUk9UbTFTVTFkdVRrWmhWbVJWVGpGU1dXRXdTa2xoVmxsNlQwWktNRlV5ZEhaaGF6VmFWRmRWTUZKck1VUmpWR2hxV2xkRk1tUXlVakJoZW1SVVlqRkdjMVp0Y0VoU01GSnpZakl4YUU1NlFuVmxhbWRMV2pGc05Vd3lPVmhqYm14SFUxWkNkRlZyTVVoaGFrcEhZMnRzYW1FeVkzWldWa1pyWTI1Q2ExTlVhelJPYWtKR1VWaG5jbU5JWkVOYVdFNU5TekJ3TmxsdFNrZE9hMmhXVlZoU1ZXSnNXbXBhVkZaVVlsRndhbE51WkhWU1YyeHBZVEZLUjFSWFRuVmlhekI1VFc1cmVGSnVUWEphVkZreFlsZHZkbFJYVmtWVlIyeHRXa1ZzTVZJeFp6TmlXR3MxVW5wRmVsVkZXbnBWTW5CeFltNXNZV0ZIZUVWU1JFSlBaRzA1VGtOc1JrSlpNRTVDWkRCV1FsRlhSazVOVlRGRlZGaGtSVm94YkVWV2JFbDNWVVZHVWxORE9VTlJWa1pGVVZka1dGb3dNVU5VVldSQ1RWWldhMU5zUmxKVVZURkNZakJrUkZFelRraFJWa1pXVW10S00xUlZUVXRVVlVZelVqQkZlRlpYVWtaa01GWkRURE5rVWxFd01VSlJXR1JGVlZac1MxTXlPV0ZUVjJneVdUQTFRbFZWVmsxUmJFWkNVa2RrYmxKVlNrSlNWVGxQWkROV1RGWnRUa2hoU0djeVlUQmtNV1F4V1RCaVVYQm9ZakJPTUU1SVdsaGFWVnBXVjFSYWFrNUZhekJOYlU1VFRqRmpjbGxyV2pOYWJVNU5Va2hXVmt3eGNESmpSbXMxV210T2RVOVlaR3RSYWtZeFlXMDFORTlWTVdGUFZHY3hUWHBHVVZGWVRYZFRWbkJWUTI1U2JscHVWWGhVTUVaSVZUSlNhbFo2YUZaT1JrSXpUVWRhVlZVd05WSlhTSEJ5WTBaa2FXRkhNWHBTYWtadFZERndlbEZVV2xGTlZXUnFVakI0V21KdWNHOVVWRnBFVXpOa1QyTnNhSFZSVld3MFVWUk5TMkpIUm5GU2JGWldWa1JqZWxvd1VuTlJWazU1VjFoV2VHTnJTakJaYTFweVltMU9ObUpyVVhkUmJXOTJVMjB4UWxkdE9XcFpNRTVDWXpOQ1RsTkVhRmxrYkVKWlQxaEZlR1ZUT1haVFUzUnRVV3RKZWxKbmNGUmtWM1J2VVZWd1JFdDZVa3ROYkZKRFZGUkdia3d3Vm01UFZHUTFZekp6TTJScVVYWmpTRkY0WlZSV1lWVldVbTVTYlhCRVpGYzFkVmxyUlRCVFJVVTBWVlZvUjA0eU1VMVZSMjgwWXpKS00yTnJXalpEYWtvMFdsVmtjR0pYT1dGT1JYQm9XbFJvVVdReVkzZFBWVFZ4WkZSV2EwOUhSazlQV0U1elpEQXdkbE5IY0VaUFZVWmFVa1pHTVdOdFJubE5WVWwzWWpOYU0yTlZjRzFUYmtZellqQnNNVk15Vm1oV00xVkxVWHBqTkZCUmIzUk1VekIwVEZWV1QxSkRRa1JTVmtwVlUxVmFTbEV3UmxWU1V6QjBURk13ZEVOblBUMEtJQ0FnSUdOc2FXVnVkQzFyWlhrdFpHRjBZVG9nVEZNd2RFeFRNVU5TVldSS1ZHbENVMVV3UldkVlJrcEtWbXRHVlZKVFFreFNWbXQwVEZNd2RFeFJjRTVUVld4R1kwVkdTbEZyUmtKVE1FNUNWVlZXUWsxVk1IWmpWVGxUWVVSQmNtTnFWbTVaTUdoWlQxZDRkbE5YYUhsT1dHZDRVa1ZzY2xNeU9EUmlWV2haWVROVmVFNUZPVnBOZVhRMldsWmFWVkpXUm5CRGFrcFdWV2wwZFZVeFNuZE5SMlJKVDFka1dXSXliRzVVYXpFeFRtMW9jazB6WkZKYWFscExZVWR3ZFdRd1pIVlZWWGh0WVRJd01tTnFaR3hhZVhSelV6QlNiMWxZUWtaa2JVcHRZMVphVmxKRVZsaE1NREJMVGxac00xVkhNV2xpVlRSNFRteFdWbEl5T1RSa2JtY3lVMVV4Y0ZScWFFMVBSMUpKVFd0d2VsVnVRa2hTVmtwYVpXNUJlRkp0TVROVk1IQmhWVWhTVDFwV1JrWmFWWEJaV201b1NFMVZkRlJoVlRCNFduZHdORTR5WkZaa01IUjVaVWhuTVdOdVNrTk5ha3BWWkVWMGIxRXhXbGhVVm14YVZERmtjRmR1U2pKVk1scFJaVlZLY1ZSRGRHOVpXRnBLVmxkamNsZHJWak5aVmtKYVZqTk9iMlZXVGtWUFZrcERUVzVXYzBOcVFuRk5NM0I1VlZaR1JWTkVXblZSVlZreVpETlpNR0pyTlRCak1XaDJXa1pLUkUxVk9XdFdibWN6WWtWMFlXUXlOVVJaTVU1TFpGWktSbFpZYURWYVYwNDJXVzFLVFZaV1pEWk9WR1I1WWxkR1VVOUlaMHRPUlRCeVUycHJkMkZVVW1GYWJsWnBWRVJDYVZkSFRUUldNMmhNVkRBNWJWTnRNVWhXVlRGUlZWUkpjbG96YUVKUmJtUktVa1ZHVWxGVlNrSmlNR3hEVVZWU1FsVkVTazlXVm1SUVdsUkNhVk42YUhoWlVYQlVaV3RGZG1OV1ozcGtNMUl3WTFkck1WTnFSa1JMTVdSd1UyMUtlbFpYYUVoV1Z6Rk1WRWhvVkdSc1pIbFVhbEV6V1ZVMU1HUXpValJoTUU1TVRUQk9VRk13ZEc5aGJuQjFXa2RrY0ZSRWJGQmxiV2N4UTIxS1dWWXlWazVSYW1oRFRraG9SbUpyV2tWYWFrSm9aR3BTTUdGdFdteGxiVlV5VjBaS2IySnNUVFZrTUU1c1lXMUtOVTVyYUhaaU1qa3hWV3hLUmxScVVrbGxiRlp5VFVWc2NGTnNielZsVjNCT1YxVnpTMkpVWkZoWFZsWnRZak5hTVZSR1pHeE5hbG8yVkVoV1MwNVVVbWhsVjFaTFUydEtTVk5WTlZoUFZUVnhVV3RLZDFvd05ERlJiRkpTVkVab1RXTXhhRmRTYkVKMllXMUtWMlF4UWs5Tk1IUk9WVWRTTldOM2NIZFdibVIxV1RCc1NrNHdiSGRVTURWaFlURlpNV1F5TVdGaFNIQXdWMnRhV1ZFd2R6SlVWRVpzVGtad1IwOUVRblZUYWxwSFRUQnJkbUpxYkV4amFtUndZVzFLUWxSNlpGTmtNMHBoWVVWR1IxVkZlRmxEYmtKWVZHdGFVVmxWU2taTmJGSXpUa2hLUm1KR1dtdGxhMUl3VFVjNGQxVXhXbXRVYkVwVlZVYzVjVk5xVmpSTlV6bEtWRVYzZVdScVdYWlRiVlpJVlVkd1VHUXhXbWhTVmtGeVRVVk9XVmxVU2xoU1ZtOUxWRzVPYVdSRWJHRmhNRTV1VjFWV1FrMVhhR2xaTUhSSFRVaFNjMVpXUW10a1ZXUnZVMnh3VGxvelFURlZSbXh1VkRCSmVGa3hTalZVUlZFd1dtdDBiMDVWTVVKalNHaDFUMVJOTW1OR2JEQldSRUV5Vm5kd2JtRnRNVmhSYXpGNVdsZHdkMUZyTURGVk0xWlZZMU4wVEZKVmVGTmpNMDVWVjBjNVRGTjZTa2xUUmtwNFkydFpORk5ET0hoalNFVjRUa2hhTmsxWGNERlVWVTVMVDBSU1Jsb3hUbXRrUmxaTlkycGFXa051VlRGYWJFSlFZek5TV0ZGdVRrZFZSbHBUWVRCV1dFOVRPV3RTYm1kM1ZFUnNibVZGZUhoU1YzaGFaV3hrVlV0NWRFTlRWa1pEVFdsemVWWlZTbEpqUkd3elQwZE9iVlpVUWtSYU1XeEdVVk01ZFdFd05FdFRWbFpoVlZWd05rOUlaSFZqZVRsTVpFWlNRMUp0Um5OT1dGSlhTekpXV0U5VldqRmFNbXd4V21wVmRrOVhNVzFPYWxwVFRVWlplVTVYU1hkYU0xSk9XbGRPTkU5WVdqSlNNbEl3V2tkYWRXRkZPVE5XZDI5NlZWaEdjV0ZGTVVka1ZGcFVUVVpzVmxSR1JrZGxWbkEyVTFkV01tUjZRbEpqVkdoNFRtMVNXRmRyZUdsbGExWnpUVEJLVkdJeU1ETlRSMlIxVmpCME5HVnVRalZYVlZwNFlqQldkV0l4UVRGVGFtUk5RMjVvTTJWV2JFdFdNREZOVWpOa2NWWkdVakpsYlZsNFZFVkdNR0Y2WkhGT1ZHZDJWakp6TTJKcWJHeFRWM0F6WkZaa1RGUlZUbTVYVlZaQ1pGVjRNMWxyV2paTlZ6bENaR2s0ZG1WRVVucFBWemxoWVVaUlMxRnRiekJYUjJ4VlZXeFdjMlZGV1RGaWVrNVJVVzAxVUdGdVpGcE5WMUpHWkZSU2NsRlVXbTVoTTFwUVUxYzFTRll3ZUdGVmJURXpWbFY0VTFaWGIzcFBSa0V6VldrNVZWZFdSbHBYUkZaMlYwZGtObFIzY0dsamFrSlpXa2R3VEZKV1ozbFRWMFV5WVd0d2RVNVdXbk5TZW1oSldXdEdObFJ1UWxaWGJrMTVWVEpKZWxack1YVldSMlF4VkZWV1FsTldZekpPTTFKMlpHeGtkRkV6U21sU00yaDFXV3hDZDJGR1JUUkRiVVY1V2xSRmVFNUlWa2hoUkVaU1pHdHdjRlZ1WkVsWmFtUlBWMFJXVmxFeVpGcFNWVVV6VjFaR2VWTklhM2xsYm5CMlRrVjBXbGRyVWpCV1ZrNVZWMFZLYUdSR1NsRlBSbFoxV201S2NHUnJjSEZhYkZGTFdtMTROV1F3VGxwTE1rNUZUbTFPTTFFd09VNVNlbFpLVVcxS01Gb3lVbmhNTTBwMFdqSTFUazVyYUhaVGJGVjZXbTVPYlZacmR6UmpNMEpxVkcwNGVXUkZlRWhoYWxaeFdXeFdOVk5yVm1oT2JsSjRUVkZ3YkZOcVJrUmlWbGt6VGpJNWNGWkhPVVZrYmtaTlUycHJlVkpJVmtSTE1uZzBVakowTUdRd1pGRk1NSE16VVROd2VGcFZhRVJTVjFGeVpIcFplazR4YUhkVFNFMTNXVzV3YW1SVlNteGhhazUyWTFoak0wTnNRbmRXVmtwaFZURldSRm94YkVOaU1WcHJVMFV3Y2xNelJraFhWa2t3VTIxSmRsUkhXa05sUjFZellsZGtSR015VWxkalZUbFlWbTVhY1dWdVNUUlNiVGwzWTBoV1ZsSkhSbnBrVlZwMFRUTlNibFZ1VFV0T01rWTJWMFZPWVU1VWF6RldiV3g1VG1wYVZsVXlaM2hoUjJSUlRUSktRbGRzUW5SalZteERXbFZ2TVdWR1duZFdWMFpXVWxoU1NGUnFXbmRSTVdOMldrVTFVRnBFV201UldIQXpZME4wU0ZwdFNUUlhaM0F6U3pCek0xUkZhRkJSZVhSTFRrYzFhRTVITlVoUFJscFBZbXBqZWxkc1VsVlRSRW8wWld0U1MyTXhhM2hUZWxwb1UxWktNRlJzUmtsVVJWcERVakJHZGxWcmFFeE5NVVU1VUZGdmRFeFRNSFJNVlZaUFVrTkNVMVV3UldkVlJrcEtWbXRHVlZKVFFreFNWbXQwVEZNd2RFeFJiejA9Ci0gcGF0aDogL3Zhci9saWIva3ViZWxldC9jYS5jcnQKICBwZXJtaXNzaW9uczogMDY0NAogIGVuY29kaW5nOiBiNjQKICBjb250ZW50OiBMUzB0TFMxQ1JVZEpUaUJEUlZKVVNVWkpRMEZVUlMwdExTMHRDazFKU1VNeVJFTkRRV05EWjBGM1NVSkJaMGxTUVVzelRuTkNUemRuVXpBclEydGhWbWg0TXpKc2VsVjNSRkZaU2t0dldrbG9kbU5PUVZGRlRFSlJRWGNLUmxSRlZFMUNSVWRCTVZWRlFYaE5TMkV6Vm1sYVdFcDFXbGhTYkdONlFXVkdkekI0VDBSQmVFMVVSWGRQVkVWNlRVUmtZVVozTUhsUFJFRjRUVlJGZHdwUFZFVjZUVVJrWVUxQ1ZYaEZla0ZTUW1kT1ZrSkJUVlJEYlhReFdXMVdlV0p0VmpCYVdFMTNaMmRGYVUxQk1FZERVM0ZIVTBsaU0wUlJSVUpCVVZWQkNrRTBTVUpFZDBGM1oyZEZTMEZ2U1VKQlVVTXlibll2YTNKRVN6WkdObmhGS3poeVFrSndWbFpRYzFwMVQzcHpWa05aZEhNME4wczNhQzlpVjI1VWIyOEtXWG93T1NzMVFVVk9UbFJ5UVU0dlEydG1WV3hFWlZKWGFuY3hSRFZ3YUVsakswOWhZMDFSTkVac1RXVm5ZV1UyU2podVEyWjBWR0lyUkhkbVJYVTRSQXBUT1RGSWNISnJjbmR2Wnk5cFRFNDBWSFJVWnpsNmVVNHpXSFZ0ZHpGUk5HTm1jREZ0TkdaSmEwVlJWM1I1UjNKeE9HSXlURVpHYkZsVmFVcG5OV2xyQ205b0x6Vm1ja0ZWVDNnM09ESjFhRmw2Y3l0WmFUQXdObmN3YzFweU9TOVBkbnBoZDBrelJUbDBRMlppTW5wVlRXMUpTRkZEYVdwVk1sWTRWV1ozTjBnS1JYVnFhbVJpUTFCdllTODNWQzlHTWxkYWFGbGxRblF2YW1VcmFWTm1jWEoxYm05aWNsaE9XaTlFZUcxblEzTnBTek5rTVdGeloxRlhNemR1U2twc1ZBcFVTV2gwY1RORU9YUnpjVkZQUzJvck5sRTRTemN5VGpCd1VtTnFUSEJPUlV4Rk9XNXJSa1U1UVdkTlFrRkJSMnBKZWtGb1RVRTBSMEV4VldSRWQwVkNDaTkzVVVWQmQwbENjR3BCVUVKblRsWklVazFDUVdZNFJVSlVRVVJCVVVndlRVRXdSME5UY1VkVFNXSXpSRkZGUWtOM1ZVRkJORWxDUVZGQloxRTJZV2dLVDFSdU9YQm9VelZUYzBGWlYzVXlWekZ5ZGxGcFJ6UllTRGRxVHpkcWVsbENVVXcwTVZvNGFrRTVZblpwY1dRNFkzRnZRWFV3VVV4QmRVeFlaVGxFT1FwalprSktSbE5YY1dsVGIySkNWMFUzYzNFd1JVVjFaakZIZEZWcGFVWkxVMDVEWTJReFZGbGFaRzQ0TDJjeWRsZ3JUek5FUXpSbGVVOUZRVUZVYUhWcUNqWktUVVJXTWt0dVpIVlViMFJxWTBSSmNEQm1ZMVl6U0RocVVtNXhRVk5JVDFWM1VrNTZRalJpVUd3d2QxaDFRWGxyVUVKc01rRkVWVzlUUVdONE1Xa0tRMkpRWjNZMVVWbDFWMFo1TXpNeWVYWnpjSEF4TDBvcllWTmhiblpTTkd4M2NGWk1jVGhWZDJkd01GSnlXbEZwWkcxdmJ6UkliMVZWVkRsTGMwNXRPQXBRYWxKcFF5OWhabFZZTlhoSVpXVm5NWGhOY21OS1oyOXdXRUpSUldRNGJEZEpkbWRxVm1kNWVGcFdjMVZUUTFKTk5HOUhLMHAzVm14UGJVdHBkRlI2Q2tWWFkyNW5SWFp5YTIxbk16RTFUV0lLTFMwdExTMUZUa1FnUTBWU1ZFbEdTVU5CVkVVdExTMHRMUW89Ci0gcGF0aDogL2V0Yy9zeXNjdGwuZC85OS1rOHMtZ2VuZXJhbC5jb25mCiAgcGVybWlzc2lvbnM6IDA2NDQKICBjb250ZW50OiB8CiAgICB2bS5tYXhfbWFwX2NvdW50ID0gMTM1MjE3NzI4CiAgICBrZXJuZWwuc29mdGxvY2t1cF9wYW5pYyA9IDEKICAgIGtlcm5lbC5zb2Z0bG9ja3VwX2FsbF9jcHVfYmFja3RyYWNlID0gMQogICAgbmV0LmNvcmUuc29tYXhjb25uID0gMzI3NjgKICAgIG5ldC5jb3JlLm5ldGRldl9tYXhfYmFja2xvZyA9IDUwMDAKICAgIG5ldC5jb3JlLnJtZW1fbWF4ID0gMTY3NzcyMTYKICAgIG5ldC5jb3JlLndtZW1fbWF4ID0gMTY3NzcyMTYKICAgIG5ldC5pcHY0LnRjcF93bWVtID0gNDA5NiAxMjU4MjkxMiAxNjc3NzIxNgogICAgbmV0LmlwdjQudGNwX3JtZW0gPSA0MDk2IDEyNTgyOTEyIDE2Nzc3MjE2CiAgICBuZXQuaXB2NC50Y3BfbWF4X3N5bl9iYWNrbG9nID0gODA5NgogICAgbmV0LmlwdjQudGNwX3Nsb3dfc3RhcnRfYWZ0ZXJfaWRsZSA9IDAKICAgIG5ldC5pcHY0LnRjcF90d19yZXVzZSA9IDEKICAgIG5ldC5pcHY0LmlwX2xvY2FsX3BvcnRfcmFuZ2UgPSAxMDI0MCA2NTUzNQogICAgbmV0LmNvcmUubmV0ZGV2X21heF9iYWNrbG9nID0gMTYzODQKICAgIGZzLmZpbGUtbWF4ID0gMjAwMDAwMDAKICAgIGZzLmlub3RpZnkubWF4X3VzZXJfaW5zdGFuY2VzID0gODE5MgogICAgZnMuaW5vdGlmeS5tYXhfdXNlcl93YXRjaGVzID0gNTI0Mjg4CiAgICBmcy5haW8tbWF4LW5yID0gMjYyMTQ0CiAgICB2bS5tZW1vcnlfZmFpbHVyZV9lYXJseV9raWxsID0gMQogICAgbmV0Lm5ldGZpbHRlci5uZl9jb25udHJhY2tfbWF4ID0gMTA0ODU3NgotIHBhdGg6IC9vcHQvYmluL2hlYWx0aC1tb25pdG9yCiAgcGVybWlzc2lvbnM6IDA3NTUKICBjb250ZW50OiB8CiAgICAjIS9iaW4vYmFzaAogICAgc2V0IC1vIG5vdW5zZXQKICAgIHNldCAtbyBwaXBlZmFpbAoKICAgIGZ1bmN0aW9uIGRvY2tlcl9tb25pdG9yaW5nIHsKICAgICAgZWNobyAiRG9ja2VyIG1vbml0b3IgaGFzIHN0YXJ0ZWQgISIKICAgICAgd2hpbGUgWyAxIF07IGRvCiAgICAgICAgaWYgISB0aW1lb3V0IDYwIGRvY2tlciBwcyA+IC9kZXYvbnVsbDsgdGhlbgogICAgICAgICAgZWNobyAiRG9ja2VyIGRhZW1vbiBmYWlsZWQhIgogICAgICAgICAgcGtpbGwgZG9ja2VyCiAgICAgICAgICBzbGVlcCAzMAogICAgICAgIGVsc2UKICAgICAgICAgIHNsZWVwICRTTEVFUF9TRUNPTkRTCiAgICAgICAgZmkKICAgICAgZG9uZQogICAgfQogICAgZnVuY3Rpb24ga3ViZWxldF9tb25pdG9yaW5nIHsKICAgICAgZWNobyAiV2FpdCBmb3IgMiBtaW51dGVzIGZvciBrdWJlbGV0IHRvIGJlIGZ1bmN0aW9uYWwiCiAgICAgIHNsZWVwIDEyMAogICAgICBsb2NhbCAtciBtYXhfc2Vjb25kcz0xMAogICAgICBsb2NhbCBvdXRwdXQ9IiIKICAgICAgd2hpbGUgWyAxIF07IGRvCiAgICAgICAgaWYgISBvdXRwdXQ9JChjdXJsIC1tICRtYXhfc2Vjb25kcyAtZiAtcyAtUyBodHRwOi8vMTI3LjAuMC4xOjEwMjU1L2hlYWx0aHogMj4mMSk7IHRoZW4KICAgICAgICAgIGVjaG8gJG91dHB1dAogICAgICAgICAgZWNobyAiS3ViZWxldCBpcyB1bmhlYWx0aHkhIgogICAgICAgICAgcGtpbGwga3ViZWxldAogICAgICAgICAgc2xlZXAgNjAKICAgICAgICBlbHNlCiAgICAgICAgICBzbGVlcCAkU0xFRVBfU0VDT05EUwogICAgICAgIGZpCiAgICAgIGRvbmUKICAgIH0KICAgIFNMRUVQX1NFQ09ORFM9MTAKICAgIGNvbXBvbmVudD0kMQogICAgZWNobyAiU3RhcnQga3ViZXJuZXRlcyBoZWFsdGggbW9uaXRvcmluZyBmb3IgJGNvbXBvbmVudCIKICAgIGlmIFtbICRjb21wb25lbnQgPT0gImRvY2tlciIgXV07IHRoZW4KICAgICAgZG9ja2VyX21vbml0b3JpbmcKICAgIGVsaWYgW1sgJGNvbXBvbmVudCA9PSAia3ViZWxldCIgXV07IHRoZW4KICAgICAga3ViZWxldF9tb25pdG9yaW5nCiAgICBlbHNlCiAgICAgIGVjaG8gIkhlYWx0aCBtb25pdG9yaW5nIGZvciBjb21wb25lbnQgJGNvbXBvbmVudCBpcyBub3Qgc3VwcG9ydGVkISIKICAgIGZp"),
				LinuxConfiguration: &compute.LinuxConfiguration {
					DisablePasswordAuthentication: to.BoolPtr(true),
					SSH: &compute.SSHConfiguration{
						PublicKeys: &[]compute.SSHPublicKey{
							{
								Path: to.StringPtr("/home/admin/.ssh/authorized_keys"),
								KeyData: to.StringPtr("ssh-rsa sample-key-here"),
							},
						},
					},
				},
			},
			NetworkProfile: &compute.NetworkProfile{
				NetworkInterfaces: &[]compute.NetworkInterfaceReference{
					{
						ID: &nicID,
						NetworkInterfaceReferenceProperties: &compute.NetworkInterfaceReferenceProperties{
							Primary: to.BoolPtr(false),
						},
					},
				},
			},
			AvailabilitySet: &compute.SubResource{
				ID: to.StringPtr("/subscriptionID/sample-url/avset"),
			},
		},
		Tags: &tags,
	}
}

// createPIPandNIC creates a public IP address and a network interface in an existing subnet.
// It returns a network interface ready to be used to create a virtual machine.
func createNIC(machine string, subnetInfo *network.Subnet) (*network.Interface) {


	nicName := fmt.Sprintf("%s-nic", machine)
	glog.Infof("\tCreate NIC '%s'...\n", nicName)

	enableIPForwarding := true

	nicParameters := network.Interface{
		Location: &location,
		InterfacePropertiesFormat: &network.InterfacePropertiesFormat{
			IPConfigurations: &[]network.InterfaceIPConfiguration{
				{
					Name: &nicName,
					InterfaceIPConfigurationPropertiesFormat: &network.InterfaceIPConfigurationPropertiesFormat{
						PrivateIPAllocationMethod: network.Dynamic,
						Subnet: subnetInfo,
					},
				},
			},
			//ResourceGUID: &groupName,
			EnableIPForwarding: &enableIPForwarding,
		},
	}

	cancel := make(chan struct{})
	output, errChan := interfacesClient.CreateOrUpdate(groupName, nicName, nicParameters, cancel)
	onErrorFail(<-errChan, fmt.Sprintf("interfacesClient.CreateOrUpdate for NIC '%s' failed", nicName))
	glog.Infof("\tCreated NIC '%s' successfully\n %s", nicName, output)

	glog.Infof("\tGet NIC info for %s...\n", nicName)
	nicParameters, err := interfacesClient.Get(groupName, nicName, "")
	onErrorFail(err, fmt.Sprintf("interfaces.Get for NIC '%s' failed", nicName))

	return &nicParameters
}

// onErrorFail prints a failure message and exits the program if err is not nil.
func onErrorFail(err error, message string) {
	if err != nil {
		glog.Infof("%s: %s\n", message, err)
		os.Exit(1)
	}
}

// getEnvVarOrExit returns the value of specified environment variable or terminates if it's not defined.
func getEnvVarOrExit(varName string) string {
	value := os.Getenv(varName)
	if value == "" {
		fmt.Printf("Missing environment variable '%s'\n", varName)
		os.Exit(1)
	}

	return value
}


func createClients(subscriptionID string, authorizer *autorest.BearerAuthorizer) {
	subnetClient = network.NewSubnetsClient(subscriptionID)
	subnetClient.Authorizer = authorizer

	interfacesClient = network.NewInterfacesClient(subscriptionID)
	interfacesClient.Authorizer = authorizer

	vmClient = compute.NewVirtualMachinesClient(subscriptionID)
	vmClient.Authorizer = authorizer

	diskClient = disk.NewDisksClient(subscriptionID)
	diskClient.Authorizer = authorizer
}